### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by tebriz159** [MaximKomlev/BLERadariOS#1]
Hello, I made a logo for your project and if you want to use it please comment below and I'll send you all of the files so you can add it to your project )

![b](https://user-images.githubusercontent.com/31902754/39401135-1cf8528e-4af3-11e8-8c9c-7a5dd085db41.png)

**Comment by MaximKomlev** [comment]
Thank you looks nice, but actually project name and final app name are different, also I already have icon [,](https://raw.githubusercontent.com/MaximKomlev/BLERadariOS/master/icon_app_blue_120.png) i believe it requires reviewing it, so if you have better idea, i will appreciate.
